# Generated by Django 4.1.7 on 2023-03-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        choices=[(1, "SM"), (2, "MD"), (3, "LG"), (4, "XL")]
                    ),
                ),
                ("status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=4)),
                (
                    "car_size",
                    models.IntegerField(
                        choices=[(1, "SM"), (2, "MD"), (3, "LG"), (4, "XL")]
                    ),
                ),
                (
                    "slot_size",
                    models.IntegerField(
                        choices=[(1, "SM"), (2, "MD"), (3, "LG"), (4, "XL")]
                    ),
                ),
                ("entry_time", models.DateTimeField(auto_now_add=True)),
                ("exit_time", models.DateTimeField(null=True)),
            ],
        ),
    ]
