# Generated by Django 4.1.7 on 2023-03-23 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="ticket", name="slot_size",),
        migrations.AddField(
            model_name="ticket",
            name="slot",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.slot"
            ),
            preserve_default=False,
        ),
    ]
