# Generated by Django 4.2.7 on 2024-05-01 21:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name="ticket", old_name="price", new_name="total_price",
        ),
        migrations.RemoveField(model_name="ticket", name="id",),
        migrations.AlterField(
            model_name="ticket",
            name="token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        choices=[(0, "SM"), (1, "MD"), (2, "LG"), (3, "XL")]
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "parking_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="app.parkingarea",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="ticket",
            name="slot_size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="app.slot",
            ),
        ),
    ]
